from MF.V3.Task import TaskState as MF_V3_Task_TaskState


class ConnectScanner:
    """*
    Connect the desktop engine to a scanner (desktop engine only).

    The engine negotiates capabilities with `GetProtocolInfo`, enables client
    processing, and downloads the scanner's calibration into its local
    workspace.  A `ScannerStatus` message is pushed to every client when the
    connection state changes.

    > Request example:

    ```json
    {
    "Task":{ "Index":1, "Type":"ConnectScanner", "Input":"matterandform.local" }
    }
    ```

    > Response example:

    ```json
    {
    "Task":{ "Index":1, "Type":"ConnectScanner", "Output":true, "State":"Completed" }
    }
    ```
    """
    class Request:

        """
         Client request for the `ConnectScanner` task.
        """
        def __init__(self, Index: int, Type: str, Input: str):
            # A unique identifier generated by the client.
            self.Index = Index
            # "ConnectScanner"
            self.Type = Type
            # The scanner host name or IPv4 address.
            self.Input = Input

    class Response:

        """
         Server response for the `ConnectScanner` task.
        """
        def __init__(self, Index: int, Type: str, Output: bool = None, State: MF_V3_Task_TaskState = None, Error: str = None):
            # The unique identifier generated by the client.
            self.Index = Index
            # "ConnectScanner"
            self.Type = Type
            # True if the connection was established.
            self.Output = Output
            # The current state of the task.
            self.State = State
            # A string describing the error if the task has failed.
            self.Error = Error

    def __init__(self):
        pass

