from MF.V3.Descriptors.ScannerList import ScannerList
from MF.V3.Task import TaskState as MF_V3_Task_TaskState


class DiscoverScanners:
    """*
    Discover scanners on the local network (desktop engine only).

    The engine browses mDNS for advertised scanners and additionally resolves
    the default scanner host name, so scanners running older firmware that does
    not advertise a service record are still found.  The search runs for a few
    seconds before the result is returned; run the task again to refresh.

    > Request example:

    ```json
    {
    "Task":{ "Index":1, "Type":"DiscoverScanners" }
    }
    ```

    > Response example:

    ```json
    {
    "Task":{
    "Index":1,
    "Type":"DiscoverScanners",
    "Output":{ "scanners":[{ "name":"THREE", "host":"matterandform.local", "ip":"192.168.50.115", "port":8081 }] },
    "State":"Completed"
    }
    }
    ```
    """
    class Request:

        """
         Client request for the `DiscoverScanners` task.
        """
        def __init__(self, Index: int, Type: str):
            # A unique identifier generated by the client.
            self.Index = Index
            # "DiscoverScanners"
            self.Type = Type

    class Response:

        """
         Server response for the `DiscoverScanners` task.
        """
        def __init__(self, Index: int, Type: str, Output: ScannerList = None, State: MF_V3_Task_TaskState = None, Error: str = None):
            # The unique identifier generated by the client.
            self.Index = Index
            # "DiscoverScanners"
            self.Type = Type
            # The discovered scanners.
            self.Output = Output
            # The current state of the task.
            self.State = State
            # A string describing the error if the task has failed.
            self.Error = Error

    def __init__(self):
        pass

