from MF.V3.Task import TaskState as MF_V3_Task_TaskState


class DownloadScannerProject:
    """*
    Download a project archive from the connected scanner (desktop engine
    only).

    The archive is sent to the client as a task buffer whose descriptor is the
    suggested file name.  The counterpart of `DownloadProject`, which archives a
    local project.

    > Request example:

    ```json
    {
    "Task":{ "Index":1, "Type":"DownloadScannerProject", "Input":2 }
    }
    ```

    > Response example:

    ```json
    {
    "Task":{ "Index":1, "Type":"DownloadScannerProject", "State":"Completed" }
    }
    ```
    """
    class Request:

        """
         Client request for the `DownloadScannerProject` task.
        """
        def __init__(self, Index: int, Type: str, Input: int):
            # A unique identifier generated by the client.
            self.Index = Index
            # "DownloadScannerProject"
            self.Type = Type
            # The scanner project index to download.
            self.Input = Input

    class Response:

        """
         Server response for the `DownloadScannerProject` task.
        """
        def __init__(self, Index: int, Type: str, State: MF_V3_Task_TaskState = None, Error: str = None):
            # The unique identifier generated by the client.
            self.Index = Index
            # "DownloadScannerProject"
            self.Type = Type
            # The current state of the task.
            self.State = State
            # A string describing the error if the task has failed.
            self.Error = Error

    def __init__(self):
        pass

