from MF.V3.Descriptors.ProtocolInfo import ProtocolInfo
from MF.V3.Task import TaskState as MF_V3_Task_TaskState


class GetProtocolInfo:
    """*
    Get the desktop-processing protocol version and capabilities.

    Older firmware does not implement this task; clients treat a failure as a
    server without desktop-processing capabilities.

    > Request example:

    ```json
    {
    "Task":{ "Index":1, "Type":"GetProtocolInfo" }
    }
    ```

    > Response example:

    ```json
    {
    "Task":{
    "Index":1,
    "Type":"GetProtocolInfo",
    "Output":{ "version":1, "capabilities":["scanCaptureStreaming"] },
    "State":"Completed"
    }
    }
    ```
    """
    class Request:

        """
         Client request for the `GetProtocolInfo` task.
        """
        def __init__(self, Index: int, Type: str):
            # A unique identifier generated by the client.
            self.Index = Index
            # "GetProtocolInfo"
            self.Type = Type

    class Response:

        """
         Server response for the `GetProtocolInfo` task.
        """
        def __init__(self, Index: int, Type: str, Output: ProtocolInfo = None, State: MF_V3_Task_TaskState = None, Error: str = None):
            # The unique identifier generated by the client.
            self.Index = Index
            # "GetProtocolInfo"
            self.Type = Type
            # The protocol capability descriptor.
            self.Output = Output
            # The current state of the task.
            self.State = State
            # A string describing the error if the task has failed.
            self.Error = Error

    def __init__(self):
        pass

