from MF.V3.Descriptors.ScannerStatus import ScannerStatus
from MF.V3.Task import TaskState as MF_V3_Task_TaskState


class GetScannerStatus:
    """*
    Get the desktop engine's scanner connection status (desktop engine only).

    > Request example:

    ```json
    {
    "Task":{ "Index":1, "Type":"GetScannerStatus" }
    }
    ```

    > Response example:

    ```json
    {
    "Task":{
    "Index":1,
    "Type":"GetScannerStatus",
    "Output":{ "connected":true, "host":"192.168.50.115" },
    "State":"Completed"
    }
    }
    ```
    """
    class Request:

        """
         Client request for the `GetScannerStatus` task.
        """
        def __init__(self, Index: int, Type: str):
            # A unique identifier generated by the client.
            self.Index = Index
            # "GetScannerStatus"
            self.Type = Type

    class Response:

        """
         Server response for the `GetScannerStatus` task.
        """
        def __init__(self, Index: int, Type: str, Output: ScannerStatus = None, State: MF_V3_Task_TaskState = None, Error: str = None):
            # The unique identifier generated by the client.
            self.Index = Index
            # "GetScannerStatus"
            self.Type = Type
            # The scanner connection status.
            self.Output = Output
            # The current state of the task.
            self.State = State
            # A string describing the error if the task has failed.
            self.Error = Error

    def __init__(self):
        pass

