from MF.V3.Descriptors.Project import Project
from MF.V3.Task import TaskState as MF_V3_Task_TaskState
from typing import List


class ListScannerProjects:
    """*
    List the projects on the connected scanner (desktop engine only).

    The counterpart of `ListProjects`, which lists the engine's local projects.

    > Request example:

    ```json
    {
    "Task":{ "Index":1, "Type":"ListScannerProjects" }
    }
    ```

    > Response example:

    ```json
    {
    "Task":{
    "Index":1,
    "Type":"ListScannerProjects",
    "Output":[{ "index":1, "name":"MyProject", "size":90010153, "modified":[2026,7,13,11,42,28] }],
    "State":"Completed"
    }
    }
    ```
    """
    class Request:

        """
         Client request for the `ListScannerProjects` task.
        """
        def __init__(self, Index: int, Type: str):
            # A unique identifier generated by the client.
            self.Index = Index
            # "ListScannerProjects"
            self.Type = Type

    class Response:

        """
         Server response for the `ListScannerProjects` task.
        """
        def __init__(self, Index: int, Type: str, Output: List[Project.Brief] = None, State: MF_V3_Task_TaskState = None, Error: str = None):
            # The unique identifier generated by the client.
            self.Index = Index
            # "ListScannerProjects"
            self.Type = Type
            # The scanner's project list.
            self.Output = Output
            # The current state of the task.
            self.State = State
            # A string describing the error if the task has failed.
            self.Error = Error

    def __init__(self):
        pass

