from MF.V3.Descriptors.Project import Project
from MF.V3.Task import TaskState as MF_V3_Task_TaskState
from typing import List


class PullProject:
    """*
    Copy a project from the connected scanner into the local workspace
    (desktop engine only).

    The engine downloads the scanner project's archive and imports it as a new
    local copy (it always receives a new project index).  Progress covers the
    archive, transfer and extraction phases as one range.

    > Request example:

    ```json
    {
    "Task":{ "Index":1, "Type":"PullProject", "Input":2 }
    }
    ```

    > Response example:

    ```json
    {
    "Task":{
    "Index":1,
    "Type":"PullProject",
    "Output":[{ "index":4, "name":"MyProject", "size":90010153, "modified":[2026,7,13,11,42,28] }],
    "State":"Completed"
    }
    }
    ```
    """
    class Request:

        """
         Client request for the `PullProject` task.
        """
        def __init__(self, Index: int, Type: str, Input: int):
            # A unique identifier generated by the client.
            self.Index = Index
            # "PullProject"
            self.Type = Type
            # The scanner project index to copy to the local workspace.
            self.Input = Input

    class Response:

        """
         Server response for the `PullProject` task.
        """
        def __init__(self, Index: int, Type: str, Output: List[Project.Brief] = None, State: MF_V3_Task_TaskState = None, Error: str = None):
            # The unique identifier generated by the client.
            self.Index = Index
            # "PullProject"
            self.Type = Type
            # The engine's updated local project list.
            self.Output = Output
            # The current state of the task.
            self.State = State
            # A string describing the error if the task has failed.
            self.Error = Error

    def __init__(self):
        pass

