from MF.V3.Descriptors.Project import Project
from MF.V3.Task import TaskState as MF_V3_Task_TaskState
from typing import List


class PushProject:
    """*
    Copy a local project to the connected scanner (desktop engine only).

    The engine archives the local project, uploads it to the scanner, and the
    scanner imports it as a new copy (it always receives a new project index).
    Progress covers the archive, transfer and extraction phases as one range.

    > Request example:

    ```json
    {
    "Task":{ "Index":1, "Type":"PushProject", "Input":3 }
    }
    ```

    > Response example:

    ```json
    {
    "Task":{
    "Index":1,
    "Type":"PushProject",
    "Output":[{ "index":1, "name":"MyProject", "size":90010153, "modified":[2026,7,13,11,42,28] }],
    "State":"Completed"
    }
    }
    ```
    """
    class Request:

        """
         Client request for the `PushProject` task.
        """
        def __init__(self, Index: int, Type: str, Input: int):
            # A unique identifier generated by the client.
            self.Index = Index
            # "PushProject"
            self.Type = Type
            # The local project index to copy to the scanner.
            self.Input = Input

    class Response:

        """
         Server response for the `PushProject` task.
        """
        def __init__(self, Index: int, Type: str, Output: List[Project.Brief] = None, State: MF_V3_Task_TaskState = None, Error: str = None):
            # The unique identifier generated by the client.
            self.Index = Index
            # "PushProject"
            self.Type = Type
            # The scanner's updated project list.
            self.Output = Output
            # The current state of the task.
            self.State = State
            # A string describing the error if the task has failed.
            self.Error = Error

    def __init__(self):
        pass

