from MF.V3.Descriptors.Project import Project
from MF.V3.Task import TaskState as MF_V3_Task_TaskState
from typing import List


class RemoveScannerProjects:
    """*
    Remove projects on the connected scanner (desktop engine only).

    The counterpart of `RemoveProjects`, which removes local projects.

    > Request example:

    ```json
    {
    "Task":{ "Index":1, "Type":"RemoveScannerProjects", "Input":[2, 3] }
    }
    ```

    > Response example:

    ```json
    {
    "Task":{
    "Index":1,
    "Type":"RemoveScannerProjects",
    "Output":[{ "index":1, "name":"MyProject", "size":90010153, "modified":[2026,7,13,11,42,28] }],
    "State":"Completed"
    }
    }
    ```
    """
    class Request:

        """
         Client request for the `RemoveScannerProjects` task.
        """
        def __init__(self, Index: int, Type: str, Input: List[int] = None):
            # A unique identifier generated by the client.
            self.Index = Index
            # "RemoveScannerProjects"
            self.Type = Type
            # The scanner project indices to remove.
            self.Input = Input

    class Response:

        """
         Server response for the `RemoveScannerProjects` task.
        """
        def __init__(self, Index: int, Type: str, Output: List[Project.Brief] = None, State: MF_V3_Task_TaskState = None, Error: str = None):
            # The unique identifier generated by the client.
            self.Index = Index
            # "RemoveScannerProjects"
            self.Type = Type
            # The scanner's updated project list.
            self.Output = Output
            # The current state of the task.
            self.State = State
            # A string describing the error if the task has failed.
            self.Error = Error

    def __init__(self):
        pass

