from MF.V3.Task import TaskState as MF_V3_Task_TaskState
from typing import List


class SetProcessingDevices:
    """*
    Select which side processes scan captures for this connection.

    The input is a pair of booleans `[server, client]`.  With client processing
    enabled the server streams raw scan captures (see the `ScanCapture`
    descriptor) to this connection during `NewScan` instead of processing them
    on-device.  The setting is per-connection: other clients are unaffected.

    > Request example:

    ```json
    {
    "Task":{ "Index":1, "Type":"SetProcessingDevices", "Input":[false, true] }
    }
    ```

    > Response example:

    ```json
    {
    "Task":{ "Index":1, "Type":"SetProcessingDevices", "State":"Completed" }
    }
    ```
    """
    class Request:

        """
         Client request for the `SetProcessingDevices` task.
        """
        def __init__(self, Index: int, Type: str, Input: List[bool] = None):
            # A unique identifier generated by the client.
            self.Index = Index
            # "SetProcessingDevices"
            self.Type = Type
            # Processing device flags: [server, client].
            self.Input = Input

    class Response:

        """
         Server response for the `SetProcessingDevices` task.
        """
        def __init__(self, Index: int, Type: str, State: MF_V3_Task_TaskState = None, Error: str = None):
            # The unique identifier generated by the client.
            self.Index = Index
            # "SetProcessingDevices"
            self.Type = Type
            # The current state of the task.
            self.State = State
            # A string describing the error if the task has failed.
            self.Error = Error

    def __init__(self):
        pass

