from MF.V3.Descriptors.StorageInfo import StorageInfo
from MF.V3.Task import TaskState as MF_V3_Task_TaskState


class StorageInfo:
    """*
    Get the local and scanner storage space (desktop engine only).

    The scanner space is absent when no scanner is connected.

    > Request example:

    ```json
    {
    "Task":{ "Index":1, "Type":"StorageInfo" }
    }
    ```

    > Response example:

    ```json
    {
    "Task":{
    "Index":1,
    "Type":"StorageInfo",
    "Output":{
    "local":{ "available":349709045760, "capacity":750199750656 },
    "scanner":{ "available":19096510464, "capacity":30482370560 }
    },
    "State":"Completed"
    }
    }
    ```
    """
    class Request:

        """
         Client request for the `StorageInfo` task.
        """
        def __init__(self, Index: int, Type: str):
            # A unique identifier generated by the client.
            self.Index = Index
            # "StorageInfo"
            self.Type = Type

    class Response:

        """
         Server response for the `StorageInfo` task.
        """
        def __init__(self, Index: int, Type: str, Output: StorageInfo = None, State: MF_V3_Task_TaskState = None, Error: str = None):
            # The unique identifier generated by the client.
            self.Index = Index
            # "StorageInfo"
            self.Type = Type
            # The local and scanner storage space.
            self.Output = Output
            # The current state of the task.
            self.State = State
            # A string describing the error if the task has failed.
            self.Error = Error

    def __init__(self):
        pass

