#!/bin/bash


if [ $# -lt 1 ]; then
    echo "At least one arguments is required."
    exit 1
fi

# Get the absolute script path.
SCRIPT_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

# Update __init__.py
VERSION=${1} 
echo "__version__ = \""${VERSION}\" > ${SCRIPT_PATH}/../three_api/__init__.py

# Build
python3 -m build ${SCRIPT_PATH}/..