#!/bin/bash


# Get the absolute script path.
SCRIPT_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

python3 -m  grpc_tools.protoc \
    ${SCRIPT_PATH}/../Proto/**/*.proto \
    -I=${SCRIPT_PATH}/../Proto  \
    --python_out=${SCRIPT_PATH}/../maf_three \
    --pyi_out=${SCRIPT_PATH}/../maf_three \
    --experimental_allow_proto3_optional