#!/bin/bash

# To run a specific function :  ". ./scripts/package-version && CheckTag v1.2.3"
# To run the tests           :  "./scripts/package-version"

# Print the project name (project directory name in Bevel) from the tag.
ProjectFromTag()
{
    if [[ ${1} = c[0-9]* ]]; then echo "V3Controller" && return 0; fi;
    if [[ ${1} = v[0-9]* ]]; then echo "V3Server" && return 0; fi;
    if [[ ${1} = qa[0-9]* ]]; then echo "QA" && return 0; fi;
    return 1
}

# Print the package name from the tag.
PackageFromTag()
{
    if [[ ${1} = c[0-9]* ]]; then echo "three-controller" && return 0; fi;
    if [[ ${1} = v[0-9]* ]]; then echo "three-server" && return 0; fi;
    if [[ ${1} = qa[0-9]* ]]; then echo "three-qa" && return 0; fi;
    return 1
}

# Remove the 'v' at the begining and replace the '-' by a '~'
VersionFromTag()
{
    if [[ ${1} = c[0-9]* || ${1} = v[0-9]* ]]; then 
        echo ${1:1} | tr '-' '~'
        return 0
    elif [[ ${1} = qa[0-9]* ]]; then 
        echo ${1:2} | tr '-' '~';
        return 0
    fi

    return 1
}

# Print the channel from the tag name (stable vs testing)
# fails if no match
ChannelFromTag()
{
    # Check for testing version
    echo ${1} | sed -n '/[0-9]\+\.[0-9]\+\.[0-9]\+-rc[0-9]\+$/!{q1}' && echo "testing" && return 0

    # Check for stable version
    echo ${1} | sed -n '/[0-9]\+\.[0-9]\+\.[0-9]\+$/!{q1}' && echo "stable" && return 0
    
    return 1
}

# Check if a tag matches [v*.*.*] or [v*.*.*-rc*] patterns
# @return 0 if the tag is valid
# @retrun 1 if the tag in invalid
CheckTag()
{
    PackageFromTag ${1} && ChannelFromTag ${1} && return 0
    return 1
}


#########################################
##               TESTING               ##
#########################################
# ExpectSuccess()
# {
#     if ! $1; then echo "Failed : "$1; exit 1; fi;
# }

# ExpectFailure()
# {
#     if $1; then echo "Expected to fail : "$1; exit 1; fi;
# }

# ExpectResult()
# {
#     res=$($1)
#     if [[ $2 != $res ]]; then echo $1" : got "$res" instead of "$2; exit 1; fi;
# }

# Valid tags V3Server
# ExpectSuccess "CheckTag v0.0.1"
# ExpectSuccess "CheckTag v0.1.1"
# ExpectSuccess "CheckTag v1.0.1"
# ExpectSuccess "CheckTag v8.0.1"
# ExpectSuccess "CheckTag v1.2.3"
# ExpectSuccess "CheckTag v1.0.1-rc2"
# ExpectSuccess "CheckTag v8.0.1-rc28"
# ExpectSuccess "CheckTag v1.2.3-rc67"

# Valid tags QA
# ExpectSuccess "CheckTag qa0.0.1"
# ExpectSuccess "CheckTag qa8.1.1"
# ExpectSuccess "CheckTag qa1.0.1"
# ExpectSuccess "CheckTag qa8.0.1"
# ExpectSuccess "CheckTag qa1.2.3"
# ExpectSuccess "CheckTag qa1.0.1-rc2"
# ExpectSuccess "CheckTag qa8.0.1-rc28"
# ExpectSuccess "CheckTag qa1.2.3-rc67"

# Invalid tags
# ExpectFailure "CheckTag V0.0.1"
# ExpectFailure "CheckTag QA0.0.1"
# ExpectFailure "CheckTag abc"
# ExpectFailure "CheckTag v0.1.a"
# ExpectFailure "CheckTag v1.2*3"
# ExpectFailure "CheckTag abc"
# ExpectFailure "CheckTag abc"
# ExpectFailure "CheckTag v"
# ExpectFailure "CheckTag qa"
# ExpectFailure "CheckTag qa1.0.1-rc"
# ExpectFailure "CheckTag qa8.0.1-c28"
# ExpectFailure "CheckTag qa1.2.3*rc67"

# Stable channel
# ExpectResult "ChannelFromTag v0.0.1" stable
# ExpectResult "ChannelFromTag v0.1.18" stable
# ExpectResult "ChannelFromTag v0.80.1" stable
# ExpectResult "ChannelFromTag v12.0.1" stable
# ExpectResult "ChannelFromTag qa0.0.1" stable
# ExpectResult "ChannelFromTag qa5.1.18" stable
# ExpectResult "ChannelFromTag qa0.80.1" stable
# ExpectResult "ChannelFromTag qa12.0.1" stable

# Testing channel
# ExpectResult "ChannelFromTag v0.0.1-rc10" testing
# ExpectResult "ChannelFromTag v0.1.18-rc36" testing
# ExpectResult "ChannelFromTag v0.80.1-rc10" testing
# ExpectResult "ChannelFromTag v12.0.1-rc0" testing
# ExpectResult "ChannelFromTag qa0.0.1-rc10" testing
# ExpectResult "ChannelFromTag qa0.1.18-rc36" testing
# ExpectResult "ChannelFromTag qa0.80.1-rc10" testing
# ExpectResult "ChannelFromTag qa12.0.1-rc0" testing

# Project from Tag
# ExpectResult "ProjectFromTag v12.0.1-rc0" three-qa
# ExpectResult "ProjectFromTag v1.2.3" three-qa
# ExpectResult "ProjectFromTag qa12.0.1-rc0" three-qa
# ExpectResult "ProjectFromTag qa1.2.3" three-qa

# Version from Tag
# ExpectResult "VersionFromTag v12.0.1-rc0" "12.0.1~rc0"
# ExpectResult "VersionFromTag v1.0.0-rc8" "1.0.0~rc8"
# ExpectResult "VersionFromTag v1.2.3" "1.2.3"
# ExpectResult "VersionFromTag v9.8.7" "9.8.7"

# ExpectResult "VersionFromTag qa12.0.1-rc0" "12.0.1~rc0"
# ExpectResult "VersionFromTag qa1.0.0-rc8" "1.0.0~rc8"
# ExpectResult "VersionFromTag qa1.8.3" "1.8.3"
# ExpectResult "VersionFromTag qa9.8.7" "9.8.7"

