name: CD Pipeline

# The pipeline is triggered by tags being pushed.
on:
  push:
    tags:        
      - 'v*.*.*'   # Library version

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Continuous_Deployment:
    runs-on: ubuntu-latest
    
    # 1. Extract information from the tag (version number, channel).
    # 2. Build the python package.
    # 3. Update the package to the repo.
    steps:

    # Checkout the source and the submodules
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.API_TOKEN_GITHUB }}
        persist-credentials: true

    ############## 1. Extract information from the tag ##############

    # Check tag
    - name: Check tag
      run: |
        echo "Checking tag: ${GITHUB_REF_NAME}"
        source ./scripts/github-tag
        CheckTag ${GITHUB_REF_NAME}
        
    # Get version number
    - name: Tag -> Version
      run: |
        source scripts/github-tag
        echo "PACKAGE_VERSION=$(VersionFromTag ${GITHUB_REF_NAME})" >> $GITHUB_ENV

    # Get the release channel: stable vs testing
    - name: Tag -> Channel
      run: |
        source scripts/github-tag
        echo "PACKAGE_CHANNEL=$(ChannelFromTag ${GITHUB_REF_NAME})" >> $GITHUB_ENV

    # Print out info
    - name: Package Info
      run: |
        echo "Version: $PACKAGE_VERSION"
        echo "Channel: $PACKAGE_CHANNEL"


    ############## 2. Build the python package. ##############

    # Install dependencies
    - name: Install dependencies
      run: |
          sudo apt install -y twine
          pip3 install -r requirements.txt

    # Set version
    - name: Set Version
      run: echo "__version__ = \"${{ env.PACKAGE_VERSION }}\"" > maf_three/__init__.py

    # Build proto files
    - name: Build proto files
      run: python3 ./scripts/build-proto.py 

    # Build
    - name: Build
      run: python3 -m build

    # Install our package (required for the tests to find the namespace : MF.V3)
    - name: Install
      run: pip3 install ./dist/maf_three-${{ env.PACKAGE_VERSION }}-py3-none-any.whl

    # Run the tests
    - name: Test
      run: python3 -m pytest

    # Build the documentation
    - name: Documentation
      run: sphinx-build -M html ./doc/source/ ./doc/build/


    ############## 3. Upload the package and the documentation. ##############

    # Upload python package to testpypi
    - name: Upload to TestPyPi
      run: twine upload --repository testpypi dist/* -u__token__ -p${{ secrets.TESTPYPI_TOKEN }}
      #run: twine upload dist/* -u__token__ -p${{ secrets.PYPI_TOKEN }}


    # Upload the documentation
    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './doc/build/html'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4


